import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link'; //[x] prettier
import { Button } from '@mui/material';
import Loginbutton from './components/Loginbutton';
import { cookies } from 'next/headers';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoggedIn: boolean = !!cookies().get('accessToken')?.value; //쿠키의 value 속성은 쿠키의 값을 'string' 형태로 반환하기 때문
  return (
    <html lang="en">
      <body className="h-screen flex flex-col bg-white">
        <div className="h-[6.5%] w-full flex left-0 top-0 bg-[rgb(230,230,230)] items-center gap-[30px] text-black p-[20px]">
          <Button href="/" className="ml-[20px]">
            Home
          </Button>
          <Loginbutton isLoggedIn={isLoggedIn} />
          <Link href="/user/register">Sign up</Link>
          <Button href="/mypage">My Page</Button>
          <Button href="/application?page=1&size=10">App 1</Button>
          <Button href="/application2?page=1&size=12">App 2</Button>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
